"""empty message

Revision ID: 878e583ea017
Revises: 8c9b3dda533f
Create Date: 2023-01-27 13:32:22.864982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '878e583ea017'
down_revision = '8c9b3dda533f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.alter_column('img',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('url',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('height',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('hair_color',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('skin_color',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('eye_color',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('birth_year',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('gender',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('home_world',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('films',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('species',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('vehicles',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('starship',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('created',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)
        batch_op.alter_column('edited',
               existing_type=sa.VARCHAR(length=250),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.alter_column('edited',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('created',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('starship',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('vehicles',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('species',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('films',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('home_world',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('gender',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('birth_year',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('eye_color',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('skin_color',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('hair_color',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('height',
               existing_type=sa.VARCHAR(length=250),
               nullable=False)
        batch_op.alter_column('url',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('img',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###
